### ISSUE TITLE
Investigate Block bindings and/or Virtual fields as a solution for displaying Events post meta data 

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-events#2]
We want to reproduce some of the front end displays for Events that were implemented in the All-In-One Events Calendar (Ai1ec) plugin.

Since WordPress 6.5 there has been an API that enables certain core blocks to be dynamically updated during front end rendering.
Using the Block bindings API it's possible to use the `core/paragraph` block to display a particular value for a post meta field.  
Other supported blocks are `core/heading`, `core/image` and `core/button`.

There were some tutorials written for WordPress 6.5
- https://developer.wordpress.org/news/2024/02/20/introducing-block-bindings-part-1-connecting-custom-fields/
- https://developer.wordpress.org/news/2024/03/06/introducing-block-bindings-part-2-working-with-custom-binding-sources/#overview-of-custom-block-binding-sources

And there have been more since; see all posts related to Block bindings:

- https://developer.wordpress.org/news/tag/block-bindings/ 

### Requirement

To display Event details on both the single page and the events archive with appropriate formatting and style.
Here's an event from the live site's list of (past) events

![image](https://github.com/user-attachments/assets/5baa3324-6f86-4381-9a9d-3a5462238b29)

- Clicking on the date takes you to the events for that date - displayed like a diary page by hour from 8am
- Clicking on the title expands or closes the event
- Clicking on the Read more takes you to the single event
- Clicking on tickets takes you to the tickets_url 
- There may also be a featured image which acts as an event link

The single event looks like this:

![image](https://github.com/user-attachments/assets/57ed9bf5-1dfa-42ca-b7b3-c2663adb7f02)

**Comment by bobbingwide** [comment]
### Proposed solution

- [x] Use the `register_block_bindings_source()` API to register one or more custom block bindings to display the relevant fields or sets of fields. 
- [x] Implement callback functions that implement solutions using logic similar to oik's _virtual_ fields.
- [ ] In the caravan-2025 theme, create custom templates/patterns which make use of paragraphs which use the block binding API.

**Comment by bobbingwide** [comment]
![image](https://github.com/user-attachments/assets/381448fd-8f01-4936-bec6-b159dff4027f)

Here's a screenshot of a prototyped solution that contains the blocks to be put into an Event details template part that will be displayed in the single-event template.

I need to add a `ticket-url` button. This button really only needs to be displayed for future events.

**Comment by bobbingwide** [comment]
> Implement callback functions that implement solutions using logic similar to oik's virtual fields.

It should be possible to use a combination of both oik's virtual fields and block bindings.
The callback functions for block bindings can use `bw_theme_field()` passing the $key as the virtual field name.
Before doing that I'll implement the virtual fields to be used to display the individual parts of the calendar date
and also attempt to display the calendar date as a single virtual field.

**Comment by bobbingwide** [comment]
My experience of attempting to use block bindings was less than perfect. 
1. I wasn't able to achieve the results documented in https://make.wordpress.org/core/2024/10/21/block-bindings-improvements-to-the-editor-experience-in-6-7/
2. Consequently it required me to use the Code editor... which also required in depth knowledge of the attributes.

So, I decided to revisit the "Field block" solution that I'd prototyped in 2021.
See https://github.com/bobbingwide/sb-field-block

For some of the postmeta fields we only need to display the field's value... formatted using the field type's theming logic.
For other display formats we need virtual fields that reformat the data in a very similar manner to that already prototyped using block bindings. 

But it should be so much easier to use.

**Comment by bobbingwide** [comment]
> I wasn't able to achieve the results documented in https://make.wordpress.org/core/2024/10/21/block-bindings-improvements-to-the-editor-experience-in-6-7/

I believe this was due to the fact that I had not added supports `custom-fields` to the Events CPT. 
Having done this I was able to see something happening in the Attributes panel, but it didn't result in anything being displayed on the front end for my custom bindings.

The UI had created the following paragraph tag
```
<!-- wp:paragraph {"metadata":{"bindings":{"content":{"source":"core/post-meta","args":{"key":"event_contact"}}}}} -->
<p>Event when</p>
<!-- /wp:paragraph -->
```

My manually inserted block bindings were:

```
<!-- wp:paragraph {"metadata":{"bindings":{"content":{"source":"oik-events/event-when","args":{"key":"event_when"}}}}} -->
<p></p>
<!-- /wp:paragraph --></div>
```
